[package]
name = "chronoxide-core"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ahash = { workspace = true }
allocator-api2 = { workspace = true }
alp = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
crc32c = { workspace = true }
fst = { workspace = true }
german-str = { workspace = true }
hashlink = { workspace = true }
io-uring = { workspace = true, optional = true }
lasso = { workspace = true }
libc = "0.2"
opentelemetry-proto = { workspace = true }
prost = { workspace =  true }
promql-parser = "0.10.0"
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true }
smol_str = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
vortex-alp = { workspace = true }
vortex-array = { workspace = true }
vortex-buffer = { workspace = true }
vortex-dtype = { workspace = true }

[features]
io_uring = ["dep:io-uring"]

[dev-dependencies]
chronoxide-capture = { workspace = true }
criterion = { workspace = true }
clap = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }

[[bench]]
name = "labelset_store"
harness = false

[[bench]]
name = "symbol_table"
harness = false

[[bench]]
name = "head_buffer"
harness = false

[[bench]]
name = "io_reads"
harness = false

[[bench]]
name = "io_writes"
harness = false
