[package]
name = "chronoxide-ingester"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
chronoxide-core = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hyperloglog = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-proto = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["default", "spec_unstable_metrics_views"] }
prost = { workspace = true }
prost-types = { workspace = true }
rayon = { workspace = true }
rdkafka = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tdigests = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
zstd = { workspace = true }
